// ── Sheet Student Repository ───────────────────────────────────────────────────
//
// Helper functions and Sheet*Repository implementation for students.

let STUDENTS_FIRST_ROW = 2;
let FIRST_PA_COLUMN = STUDENTS.fields.length + 1;

/*
to be refactored using getData_
Problem: has the pa flags that are generated by other functions
These flags need to be updated dynamically by examining the responses sheet of the
respective pa.
*/
function getAllStudents(): Student[] {
  var sheet = SpreadsheetApp.getActive().getSheetByName(STUDENTS.sheet);
  if (sheet == null) {
    sheetLog("getAllStudents: Sheet not found: " + STUDENTS.sheet);
    return [];
  }
  var values = sheet.getDataRange().getValues();
  var heading = values.shift();
  if (heading == null) {
    sheetLog("getAllStudents: No heading found in sheet: " + STUDENTS.sheet);
    return [];
  }
  var students = [];

  for (var index = 0; index < values.length; index++) {
    var value = values[index];
    var lastCol = value.length;
    let student: Student = {
      fname: value[0],
      lname: value[1],
      email: value[2],
      projectkey: value[3],
      personalkey: value[4],
      verified: value[5],
      submittedpa: {},
    };
    if (student.email == "") break;

    for (var col = FIRST_PA_COLUMN; col <= lastCol; col++) {
      var key = heading[col - 1];
      var val = value[col - 1];
      student.submittedpa[key] = val;
    }

    students.push(student);
  }
  return students;
}

function addStudent(reg: Student) {
  var ss = SpreadsheetApp.getActive().getSheetByName(STUDENTS.sheet);
  if (ss == null) {
    sheetLog("addStudent: Sheet not found: " + STUDENTS.sheet);
    return;
  }
  ss.appendRow([
    reg.fname,
    reg.lname,
    reg.email,
    reg.projectkey,
    reg.personalkey,
    reg.verified,
  ]);
}

function saveStudent(student: Row<Student>) {
  var row = student.row;
  var ss = SpreadsheetApp.getActive().getSheetByName(STUDENTS.sheet);
  if (ss == null) {
    sheetLog("saveStudent: Sheet not found: " + STUDENTS.sheet);
    return;
  }
  var data = student.data;
  var values = [
    data.fname,
    data.lname,
    data.email,
    data.projectkey,
    data.personalkey,
    data.verified,
  ];
  ss.getRange(row, 1, 1, values.length).setValues([values]);
}

function getStudent(email: string): Row<Student> | null {
  var students = getAllStudents();
  for (var i = 0; i < students.length; i++) {
    if (students[i].email == email) {
      var student = students[i];
      return { data: student, row: i + STUDENTS_FIRST_ROW };
    }
  }
  return null;
}

function getStudents(group: string): Student[] {
  return getAllStudents().filter(function (s) {
    return s.projectkey == group;
  });
}

function getGroup(studentEmail: string): string | null {
  var student = getStudent(studentEmail);
  if (student == null) return null;
  return student.data.projectkey;
}

function studentsHeading(): string[] {
  var ss = SpreadsheetApp.getActive().getSheetByName(STUDENTS.sheet);
  if (ss == null) {
    sheetLog("studentsHeading: Sheet not found: " + STUDENTS.sheet);
    return [];
  }
  var heading = ss.getRange(1, 1, 1, ss.getLastColumn()).getValues();
  return heading[0];
}

function getStudentPAColumn_(pakey: string): number {
  var ss = SpreadsheetApp.getActive().getSheetByName(STUDENTS.sheet);
  if (ss == null) {
    sheetLog("getStudentPAColumn_: Sheet not found: " + STUDENTS.sheet);
    return 0;
  }
  var heading = ss.getRange(1, 1, 1, ss.getLastColumn()).getValues();
  Logger.log(heading);
  Logger.log("heading " + heading[0] + " " + heading[0].length);
  for (var i = 0; i < heading[0].length; i++) {
    if (heading[0][i] == pakey) {
      return i + 1;
    }
  }
  return 0;
}

function addColumnToStudent(pakey: string): number {
  var ss = SpreadsheetApp.getActive().getSheetByName(STUDENTS.sheet);
  if (ss == null) {
    sheetLog("addColumnToStudent: Sheet not found: " + STUDENTS.sheet);
    return 0;
  }
  var col = ss.getLastColumn() + 1;
  ss.getRange(1, ss.getLastColumn() + 1).setValue(pakey);
  return col;
}

function setStudentSubmittedPA(
  student: Row<Student>,
  pakey: string,
  enabled: boolean,
) {
  var ss = SpreadsheetApp.getActive().getSheetByName(STUDENTS.sheet);
  if (ss == null) {
    sheetLog("setStudentSubmittedPA: Sheet not found: " + STUDENTS.sheet);
    return;
  }
  var col = getStudentPAColumn_(pakey);
  if (col == 0) {
    col = addColumnToStudent(pakey);
  }

  ss.getRange(student.row, col).setValue(enabled);
}

function sortStudents() {
  var sheet = SpreadsheetApp.getActive().getSheetByName(STUDENTS.sheet);
  if (sheet == null) {
    sheetLog("sortStudents: Sheet not found: " + STUDENTS.sheet);
    return;
  }
  sheet
    .getDataRange()
    .offset(1, 0)
    .sort([
      { column: 4, ascending: true },
      { column: 2, ascending: true },
    ]);
}

function setStudentVerified(student: Row<Student>, enabled: boolean) {
  var ss = SpreadsheetApp.getActive().getSheetByName(STUDENTS.sheet);
  if (ss == null) {
    sheetLog("setStudentVerified: Sheet not found: " + STUDENTS.sheet);
    return;
  }
  ss.getRange(student.row, 6).setValue(enabled);
}

/**
 * Returns the number of students in projectkey who submitted the pakey
 *
 * @param projectkey
 * @param pakey
 */
function numStudentsSubmitted(projectkey: string, pakey: string): number {
  var st = getStudents(projectkey).filter(function (s) {
    return s.submittedpa[pakey] == true;
  });
  return st.length;
}

class SheetStudentRepository implements IStudentRepository {
  getAll(): Student[] {
    return getAllStudents();
  }
  findByEmail(email: string): Row<Student> | null {
    return getStudent(email);
  }
  findByProject(projectkey: string): Student[] {
    return getStudents(projectkey);
  }
  add(student: Student): void {
    addStudent(student);
  }
  save(student: Row<Student>): void {
    saveStudent(student);
  }
  setVerified(student: Row<Student>, enabled: boolean): void {
    setStudentVerified(student, enabled);
  }
  setSubmittedPA(student: Row<Student>, pakey: string, enabled: boolean): void {
    setStudentSubmittedPA(student, pakey, enabled);
  }
  getHeading(): string[] {
    return studentsHeading();
  }
  addPAColumn(pakey: string): number {
    return addColumnToStudent(pakey);
  }
  sort(): void {
    sortStudents();
  }
}
